### ISSUE TITLE
Compiling uaa packages failed as gem install ignores http proxy env

### ISSUE THREAD

**Issue by hfrenzel** [cloudfoundry/uaa-release#102]
Hi,

During an upgrade from [v69.0](https://github.com/cloudfoundry/uaa-release/tree/v69.0) to [v70.0](https://github.com/cloudfoundry/uaa-release/tree/v70.0) (cf-deploment [v7.5.0](https://github.com/cloudfoundry/cf-deployment/tree/v7.5.0) -> [v7.6.0](https://github.com/cloudfoundry/cf-deployment/tree/v7.6.0)) compiling uaa package failed.

```
Task 224950 | 23:59:32 | Compiling packages: uaa/be59e056d0396db86c1489dcfb3618f20d57268b (00:06:39)
	
                      L Error: Action Failed get_task: Task 95f9be52-1262-4ee5-51c7-a30fc0f14544 result: Compiling package uaa: Running packaging script: Running packaging script: Command exited with 2; Truncated stdout: 
...
+ gem install cf-uaac-4.1.0.gem --install-dir=./vendor/cache
	
ERROR:  Could not find a valid gem 'rack' (~> 1.5, >= 1.5.2), here is why:
	
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)

```

We require to use a proxy to connect to external urls and set the `http_proxy`, `https_proxy` and `no_proxy` accordingly with [bosh-deployment/misc/proxy.yml](https://github.com/cloudfoundry/bosh-deployment/blob/master/misc/proxy.yml) during the bosh director deployment.

Is it required to set those proxy variables somewhere else during the uaa deployment, what we missed?

**Comment by wc22222** [comment]
Thanks @hfrenzel for the PR! We are taking it.
