### ISSUE TITLE
Support for protocolHeader="X-Forwarded-Scheme"

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/uaa-release#11]
My enterprise uses X-Forwarded-Scheme for the protocol header in its ssl terminating F5s.  No idea why my F5 founding fathers chose that header.  Would you accept a PR that makes this value configurable?

https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/tomcat.server.xml.erb#L62

**Comment by fhanik** [comment]
Of course, send it our way against `develop` branch.

**Comment by youngm** [comment]
Closed in favor of PR.
