### ISSUE TITLE
Enable zero downtime change of client-ids in CF-Deployment.

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/uaa-release#121]
Right now during a bosh deploy there is downtime between when UAA rolls and updates a secret and when the client rolls (ssh-proxy or tcp-emitter etc).

There needs to be a mechanism to allow for 2 passwords (as is possible using the "change-secret REST call) during the bosh deployment.

It would be good to enable an optional second password for a bosh deploy so both the old and the new password are valid at the same time.

We could "try" to do this with UAAC and then updating the clients only but again that is not in sync with how manifests in cf-deployment are generated as the same variable is used in the client definition in UAA as in the secret reference in the component (like ssh-proxy).

We need to have a built in bosh deployment method to roll and update client ids that are included in the bosh manifest for CF.

**Comment by strehle** [comment]
to me , should be solved with
https://github.com/cloudfoundry/uaa/pull/1313
