### ISSUE TITLE
UAA does not recover from hung UAA process not receiving traffic

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/uaa-release#146]
1. We are experiencing occasional situation where the uaa job stops responding to traffic <-- this is already bad (https://github.com/cloudfoundry/uaa-release/issues/143)

2. The error handling of that scenario (and thus any similar scenario) is not effective
For 2, the issue is that there are two URLs to the UAA:
(i) via gorouter - uaa.us-south.cf.cloud.ibm.com for example
(ii) via boshdns - uaa.cf.service.internal
There is a job called route_registrar that healthchecks the UAA and it is detecting the unresponsive server correctly (good). So it triggers a route prune, and that takes care of (i) - gorouter

However, it's not awesome because as an operator you have no way of knowing this happens unless you dig into the data and see that your UAA server is not being used. All the job status continue to say 'running' in monit, the whole time

which leads on to the second issue - boshdns will only switch to unhealthy state if it sees one of the monit jobs stop running. And because they don't, and because UAA has defined no custom boshdns healthcheck, then actually boshdns continues to report it as healthy, and continues to include it in the DNS results for (ii) - uaa.cf.service.internal

You end up with a unresponsive UAA server that is still receiving traffic via the boshdns route, and as a result, it is disruptive.

**Comment by Tallicia** [comment]
This is indicated as resolved in https://github.com/cloudfoundry/uaa-release/pull/147 as found in the story.
