### ISSUE TITLE
No such thing as cf-jobs.yml

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/uaa-release#15]
https://github.com/cloudfoundry/uaa-release/blob/0d14215/jobs/uaa/spec#L56-L65

These things mention spiff, cf-jobs.yml, etc.  Seems like an implementation detail that the job spec shouldn't know about.  This info can easily become stale (already is) and misleading.

**Comment by mbhave** [comment]
@Amit-PivotalLabs thanks for pointing this out. This has been addressed by the following commit: https://github.com/cloudfoundry/uaa-release/commit/d1d59abc4f0dfc72e232695f604bddde5e2bfcf1
