### ISSUE TITLE
not redirecting to configured url

### ISSUE THREAD

**Issue by sabarivijayan-fd** [cloudfoundry/uaa-release#152]
hi every one i successfully deployed standalone uaa-release along with concourse (colocated with concourse web vm)  
and i created internal groups , then mapped LDAP with it .
when i login using UAA in concourse , authentication is successful but it is not redirecting back to concourse home page

need your input to proceed further,

**Comment by srwaggon** [comment]
Hey @sabarivijayan-fd, this sounds like a configuration issue. You could try to re-investigate the paths of creating a client in the UAA as a course for debugging why the redirection is not succeeding.

Here is a resources along that journey:
https://docs.cloudfoundry.org/api/uaa/version/74.15.0/index.html#create-6
See `redirect_url`.
