### ISSUE TITLE
UAA still not sending stack traces to syslog correctly

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/uaa-release#16]
I created the original issue that got turned into this story: https://www.pivotaltracker.com/n/projects/997278/stories/102530470

That story was delivered but I'm not really sure what was actually fixed in that tracker because stack trace lines still don't get sent to syslog correctly.

Here is an integration test case that can demonstrate the problem:
- Run uaa on a linux box with rsyslog running and syslog enabled in log4j.properties. (Any typical bosh deployed UAA job will work for this)
- Add the following rsyslog config file to `/etc/rsyslog.d/0-test-syslog.conf`.  This config will write all syslog messages with a tag starting with `vcap.` to a file with the name of the tag into `/tmp/log/`.  In the case of uaa all syslog messages should go into `/tmp/log/vcap.uaa.log`

```
$ModLoad imuxsock
$MaxMessageSize 4k
$ModLoad imtcp

$template VcapComponentLogFile, "/tmp/log/%programname%.log"
:programname, startswith, "vcap." -?VcapComponentLogFile
:programname, startswith, "vcap." ~
```
- Do something that causes an exception to be thrown in uaa.  In my environment every time uaa starts up a `YamlConfigurationValidator` stack trace is logged.  So, I used that in my test.
- Compare the output of `/tmp/log/vcap.uaa.log` with `/var/vcap/sys/log/uaa/uaa.log`.  Notice that you can see the stack trace in `uaa.log` but you don't see a stack trace in `vcap.uaa.log`.

This is happening because uaa isn't sending correctly formatted syslog messages for each line of the stacktrace.

**Comment by youngm** [comment]
A small update on this. We recently introduced some code that queries uaa frequently for users that don't exist. This causes uaa to produce many stack traces. Since the syslog tags don't have "vcap" in them the syslog forwarder sends them to /var/log/messages syslog files. This eventually fills up our root disk space causing some problems.

Anyway, just adding another side effect of this issue in hopes that it helps get it prioritized. :)

**Comment by tnwang** [comment]
Closing as https://www.pivotaltracker.com/story/show/131567727 was delivered in January.
