### ISSUE TITLE
Upgrade openJDK to fix vulnerabilities

### ISSUE THREAD

**Issue by spgreenberg** [cloudfoundry/uaa-release#167]
This release is currently using openJDK 11.0.4 which is susceptible to vulnerabilities published on Oct 15, 2019: https://openjdk.java.net/groups/vulnerability/advisories/2019-10-15. 

Can you please bump the JDK version for this release to address the vulnerabilities in openJDK?

**Comment by siennathesane** [comment]
The cloud.gov team needs this for sure.

// cc @hillaryj @bengerman13

**Comment by andrewedstrom** [comment]
It looks like to do this we will need to start using a jdk from a different source, as the JDK we were previously using (which was built for Ubuntu Trusty and came from the java buildpacks team) is no longer receiving updates.

**Comment by andrewedstrom** [comment]
We have updated the jdk! It will be included in the next release.

https://github.com/cloudfoundry/uaa-release/blob/c43dc9abbb000f7ba3854b577c02c3f77e11f25c/config/blobs.yml#L1
