### ISSUE TITLE
Remove deprecated "domain" property

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/uaa-release#17]
Property is here: https://github.com/cloudfoundry/uaa-release/blob/45b5e7f/jobs/uaa/spec#L87-L88

Removing this will help unblock this story: https://www.pivotaltracker.com/story/show/118256181

The `domain` property is a constant source of confusion for users.  See discussion here: https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/MR4MD72XCSQC7KR33E7LSE5Z3ZAGEWW4/

Thanks!
Amit

**Comment by mbhave** [comment]
@Amit-PivotalLabs We have removed the deprecated `domain` property as part of https://github.com/cloudfoundry/uaa-release/commit/935aa11a2b600c45e7d5ab78327aa6f73cbc284e
