### ISSUE TITLE
ERB code doesn't correctly emit multiple items

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/uaa-release#22]
See https://github.com/cloudfoundry/uaa-release/blob/38bc1da92d55f3947f5830f302664a5ceceaa9fe/jobs/uaa/templates/uaa.yml.erb#L194

if uaa.zones.internal.hostnames contains more than one entries this emits a string like
"- host1 - host2 - host3".  It needs to emit the items one on each line.

**Comment by tnwang** [comment]
Closed as pull request mentioned was closed after a YAML ERB refactor.
