### ISSUE TITLE
Referencing uaa.clients.login.secret in uaa.yml doesn't work since it isn't in spec

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/uaa-release#27]
See: https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/uaa.yml.erb#L20

Referencing `uaa.clients.login.secret` using p() doesn't work if using job level properties because it isn't explicitly in the spec.  `uaa.login.client_secret` does work.

**Comment by sreetummidi** [comment]
@youngm This seems more like a feature request for Bosh.

**Comment by youngm** [comment]
@sreetummidi No, it was a bug in UAA.  But not anymore now that uaa config has been refactored. :)
