### ISSUE TITLE
UAA doesn't fail fast if DB credentials are wrong

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/uaa-release#28]
From what I can tell of the code, if I give the UAA job incorrect credentials for the DB, it will get stuck for 10 minutes in a pre-start or post-start script.  And when it does fail, it can be hard to debug the reason.  Had to dig a fair bit through various logs to figure out the cause.

**Comment by tnwang** [comment]
Closing as https://www.pivotaltracker.com/story/show/124374961 story was accepted in Nov 2016.
