### ISSUE TITLE
Cannot use uaa release without saml

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/uaa-release#3]
Error 100: Error filling in template `login.yml.erb' for `bosh/0' (line 93: Can't find property `["login.saml.serviceProviderCertificate"]')

**Comment by poblin-orange** [comment]
met the same issue (trying to colocate bosh with uaa). Is there any workaround ?

**Comment by sreetummidi** [comment]
@poblin-orange UAA always starts up as a fully functional SAML Service Provider and these fields are required
