### ISSUE TITLE
AppScan found high severity open source issues in CrossSiteScripting.Reflected: Insecure Use of Load or LoadXML

### ISSUE THREAD

**Issue by appleroy03** [cloudfoundry/uaa-release#309]
I am using socket.io in my application and I have referred "https://github.com/arondn2/loopback4-example-websocket-app" for the same. However appscan is returning high severity with below(\src\websockets\websocket.booter.ts).

await super.load();

Please suggest how to fix this High severity issue.

![image](https://user-images.githubusercontent.com/10769193/127470507-72fd98c8-6733-4389-af17-54f68636b60a.png)

 
![image](https://user-images.githubusercontent.com/10769193/127471250-ad852013-a2af-4c6e-ae2b-85ca4d04fe7c.png)

**Comment by strehle** [comment]
can you provide uaa version or the uaa url you use ?
I can remember that such finding related to outdated jquery, thus created https://github.com/cloudfoundry/uaa/pull/1618

**Comment by strehle** [comment]
no relation decribed how this is linked to uaa
