### ISSUE TITLE
property links is by default set to [], conflicts with use in login-ui.yml

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/uaa-release#35]
In commit bcbf3cf270bf76a150f7ad94d35075e5660a7ecf links is given a default value of [], but this conflicts with this line in login-ui.xml:

```
<bean id="links" class="java.util.HashMap">
```

It should be set to an empty hash. The workaround is give it a value in a config file.

**Comment by sreetummidi** [comment]
The links property has been deprecated. Please use the App Launch URL under the OAuth Clients for links to show up in "Where To" section
