### ISSUE TITLE
Add option to specify PKCS12 algorithm in pre-start.erb

### ISSUE THREAD

**Issue by gcerbone** [cloudfoundry/uaa-release#358]
On a FIPS enabled stemcell, pre-start.erb fails under a Bionic based stemcell.

The issue is that the current Ubuntu Bionic based stemcell uses an older version of OpenSSL, which it is required to do to run in FIPS mode.  FIPS modules are validated against specific versions, and it is not possible to patch to a newer version without loosing validation.  There is a known bug in the validated version that when using the openssl pkcs12 command, if the option -certpbe is not used to specify an algorithm, openssl will default to a non-FIPS algorithm. 

The pre-start.erb script contains the function insert_ssl_cert which uses openssl pkcs12 to export the SSL cert.  Because -certpbe is not specified, it is failing on a FIPS enabled stemcell.  However, we have validated that passing a supported algorithm such as PBE-SHA1-3DES, everything works as expected.

I'd like the script to either check for a FIPS enabled kernel and select the correct algorithm, or the ability to specify which algorithm the script should use.

**Comment by strehle** [comment]
@gcerbone like https://github.com/cloudfoundry/uaa-release/pull/366 ?

**Comment by strehle** [comment]
See comment in PR.
