### ISSUE TITLE
Recent release notes seem to have missed uaa.url now required and new scopes to create users

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/uaa-release#36]
I recently upgraded from CF Release 241 to 245.  I ran into some property changes and some other issues that I didn't see any note for in the release notes.

* `uaa.url` is now required for some reason in 245 and it wasn't in 241
* Creating a user using the cli `cf create-user` appears to now require additional scopes that weren't required before or perhaps the error message changed? (https://github.com/cloudfoundry/cf-acceptance-tests/issues/143)

Though I don't want to make too broad of a generalization, it seems that compared to the other components that are part of CF release I run into upgrade issues with UAA, for undocumented release note items, more often than the other components.  Perhaps a possible area of improvement?

I'll try to do better myself going forward by submitting issues to uaa-release for any release note related problems like this that I run into in the future.

Thanks,
Mike

**Comment by youngm** [comment]
Nevermind about the `cf create-user` issue.  I get the same error in 241......so it must have worked before for some other reason and `uaa.url` is not that big of a deal.  I'll close this issue now.  If I come up with other better issues in the future I'll create them. :)

**Comment by youngm** [comment]
I just ran into another one.  It appears that `uaa.client.autoapprove` property was removed between 241 and 245.  This is probably one that should be documented somewhere.  Though already deprecated I don't recall seeing the deprecation or removal of the property mentioned anywhere.  Release notes would be a good place to mention that.

**Comment by sreetummidi** [comment]
@youngm The deprecation notice was sent out in Feb and again in June before the properties were finally removed. I have forwarded the same to you

**Comment by youngm** [comment]
@sreetummidi Thanks for forwarding that.  I remember seeing that now.  I guess this is just a problem of too many things to communicate to too many places. :)

I guess in this case I would have liked a reminder in the release notes that those were removed since that is where I mainly look when compiling manifest changes for upgrading a release.

**Comment by youngm** [comment]
I also see that this notice identifies in an indirect way why uaa.url is now required. :)

**Comment by sreetummidi** [comment]
@youngm You are raising a valid point about cf-release notes. From now on we will make sure that we clearly specify the spec changes happening under the UAA release for a given cf-release.
