### ISSUE TITLE
Tomcat not starting due to blocking /dev/random

### ISSUE THREAD

**Issue by mrbuk** [cloudfoundry/uaa-release#39]
Hi I am using,

PCF 1.8 and ran into an issue where Tomcat blocks after restarting the VM. As a result the UAA service is not reachable not allowing me to execute an action via bosh-cli or OpsMan. In my case when I restart the director VM the UAA often doesn't come up.

I could trace back the issue on `/dev/random` blocking in my OpenStack environment.

My `bosh-state.json` tells me that I am using the following version

```
"name": "uaa",
"version": "12.6"
```

I mitigated the issue by replacing 
```
securerandom.source=file:/dev/random
```
with 
```
securerandom.source=file:/dev/urandom
```
in the `java.security` by running the following as `root` in the bosh director vm

```
java_security_file=$(find /var/vcap/ -path '*/uaa/*' -name java.security); \
  grep 'securerandom.source=file:/dev/random' ${java_security_file} && \
  sed -i.orig 's|securerandom.source=file:/dev/random|securerandom.source=file:/dev/urandom|g' ${java_security_file}
```

Instead of changing things in the `java.security` file one could add it as a system property to the monit start script.

I would recommend changing the default setting to `/dev/urandom`

**Comment by fhanik** [comment]
We believe this can be accomplished by setting the manifest property `catalina_opts`

https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L35-L37

If that is not the case, feel free to reopen this issue
