### ISSUE TITLE
login.self_service_links_enabled doesn't accept a boolean false

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/uaa-release#41]
A string "false" works though.  It appears this is because of the template logic here: https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/login.yml.erb#L121

Perhaps you can check for .nil? instead?  Or I guess another option is to disable self service links by default in uaa but `true` by default in the job spec.  Either way having to specify a string `"false"` is not very user friendly.

**Comment by sreetummidi** [comment]
This is being addressed with UAA 4.0
