### ISSUE TITLE
default serviceProviderKeyPassword to ""

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/uaa-release#44]
In reference to https://github.com/cloudfoundry/bosh-deployment/pull/5

**Comment by fhanik** [comment]
@cppforlife we may not be able to do this. no credentials should have default values according to the powers that dictate our security policy

**Comment by youngm** [comment]
@fhanik an update to the release notes adding this as a required field then in addition to the other serviceProvider* properties would be nice.  With a note that '""' can be used if your key doesn't have a password.

**Comment by fhanik** [comment]
Completed yesterday. Thanks for the feedback!

https://github.com/cloudfoundry/uaa-release/releases/tag/v23
