### ISSUE TITLE
Direct Token Exchange with OIDC Provider

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/uaa-release#50]
Hi,
this is a feature request, which I have discussed with @sreetummidi in Slack. We currently face the challenge that we have on central OIDC Provider for an infrastructure. This OIDC Provider is independent of the CF installation and issues JWT, which shall be usable at different endpoints. E.g. the token should be usable at an OpenStack installation and CF at the same time.

The current behaviour in context of OS is as follows:
- User logs in at the central IdP
- User gets a token from the IdP and we use this token to authenticate against Keystone with `Authorization: Bearer iojrevijoBlaBla`
- Token is verified against the IdP and an OS Scoped Token is provided
- With this token we can do REST API Calls and gather information of the OS APIs

It would be nice to have the same workflow for CF as well.

**Comment by jhiemer** [comment]
Wrong project, moved to uaa.

**Comment by jhiemer** [comment]
@sreetummidi regarding https://github.com/cloudfoundry/uaa/issues/532 is there time frame, when this will be released? Is there a proper way of using a prerelease for testing by checking out the repository?

**Comment by sreetummidi** [comment]
This will be available in 4.5.0 which will be available this week
