### ISSUE TITLE
Add link to CI on readme

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/uaa-release#53]
On https://github.com/cloudfoundry/uaa and https://github.com/cloudfoundry/uaa-release readmes can we put in the link to CI please?

**Comment by DennisDenuto** [comment]
Hi @drnic we currently do not have a publicly visible pipeline to show `uaa-release` running our `CATs` and `IDATS` tests.

We have an upcoming [epic](https://www.pivotaltracker.com/story/show/154753378) where we can discuss making some of our pipelines publicly visible.
