### ISSUE TITLE
pre-start script fails if certificates are changed

### ISSUE THREAD

**Issue by aemruli** [cloudfoundry/uaa-release#58]
If I extend the certificates in the director config and thus in the /etc/ssl/certs/ca-certificates.crt on the instance, then the update of the UAA fails due to an error in the https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/pre-start script. 

I assume this is due to the fact that the keytool throws an exception because the certificate exists. I would suggest to delete the $TRUST_STORE_FILE before importing the certificates that solves a few corner cases which come into my mind (certifcate added, removed, changed etc.). Deleting the $TRUST_STORE_FILE will anyway only happen if there is really a change in the certificates.

**Comment by fhanik** [comment]
@aemruli hi Agim, the trust store file is deleted each time we process it

https://github.com/cloudfoundry/uaa-release/blob/053678cb243b1e88dd60eaa32a322f9b97dbe329/jobs/uaa/templates/pre-start#L21-L21

Do you have more info on the error you are seeing, or are you possibly running an older version?

**Comment by sreetummidi** [comment]
@aemruli Any updates?

**Comment by aemruli** [comment]
@sreetummidi indeed the trust file seems to be deleted. I have to further investige why the script failed during update of the certificates. Unfortunately due to the -e switch in the beginning there is not much information I got. We I could just verify that after deleting the $TRUST_STORE_FILE the script finally executed.

**Comment by fhanik** [comment]
@aemruli Could this have been fixed in a later version?

This bugfix https://github.com/cloudfoundry/uaa-release/commit/053678cb243b1e88dd60eaa32a322f9b97dbe329#diff-07254eb4d32d216bf8351eef3604bfb0

**Comment by fhanik** [comment]
Closing. Inactivity and no other reports of this issue.
