### ISSUE TITLE
OpenSSL Ciphers

### ISSUE THREAD

**Issue by lcacciagioni** [cloudfoundry/uaa-release#59]
I'm seeing that we currently use the java ssl implementation ([here](https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/tomcat.server.xml.erb#L51)), under heavy load this can have an impact in performance, so what do you think if we use the APR connector to declare the ssl ciphers for openssl like it is explained in the Tomcat wiki [here](https://wiki.apache.org/tomcat/HowTo/SSLCiphers).
The result can be something like:
```
SSLCipherSuite="DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384"
```

**Comment by sreetummidi** [comment]
The following ciphers are being user: https://github.com/cloudfoundry/uaa-release/blob/f9195a32901212ca17aed3fce10d607b031b0756/jobs/uaa/templates/config/tomcat/tomcat.server.xml.erb#L50

This is per recommendation of the security team
