### ISSUE TITLE
Automation build release for 76.16.0

### ISSUE THREAD

**Issue by max-soe** [cloudfoundry/uaa-release#619]
Hey everyone,

We are currently confused because the automation of this repository build a new bosh release:
https://github.com/cloudfoundry/uaa-release/blob/develop/releases/uaa/uaa-76.16.0.yml
But there are no release notes and no new version of the uaa. Can you please check why this version is released?
Was this an accident or intended?

**Comment by strehle** [comment]
sorry , the release was created from our pipeline but there is no need to consume it, but also no problem if you do so.
https://github.com/cloudfoundry/uaa/releases/tag/v76.16.0
