### ISSUE TITLE
post-start scripts failed. Failed Jobs: uaa

### ISSUE THREAD

**Issue by cwb124** [cloudfoundry/uaa-release#67]
Hey folks,

First real crack at OS CF and running into an issue when deploying the latest CF release, it's breaking on the uaa instance.  Here's the error in the --debug:

ERROR -- DirectorJobRunner: Error updating canary instance: #<Bosh::Director::RpcRemoteException: Action Failed get_task: Task 78fcf8fd-30d7-4605-5396-50219ee005ce result: 1 of 1 post-start scripts failed. Failed Jobs: uaa.

If I do a monit status within the VM, everything looks good except Process 'uaa':
Process 'uaa'
  status                            Connection failed
  monitoring status                 monitored
  pid                               11919
  parent pid                        1
  uptime                            0m 
  children                          10
  memory kilobytes                  92936
  memory kilobytes total            108928
  memory percent                    9.1%
  memory percent total              10.7%
  cpu percent                       97.9%
  cpu percent total                 97.9%
  port response time                0.000s to localhost:8989/healthz [HTTP via TCP]
  data collected                    Fri Aug  4 15:19:37 2017

I looked at the post-start script in the /var/vcap/jobs/uaa/bin directory and the error seems to be a result of a failed health check.  The line in the script that tells me this:
'echo "uaa-post-start - post start failed - server failed to start successfully at `date`'

If I look at the health_check script it tries to run a curl against 127.0.0.1:8989/healthz.  When I try that curl command manually, I get the following error:
'curl: (56) Recv failure: Connection reset by peer'

I am stuck at this point.  I assume that url should return successfully.  But it's not.  How can I figure out why and how might I fix it?  Appreciate any direction as I am absolutely stuck here.

**Comment by sreetummidi** [comment]
@cwb124 Can you please share the UAA Log

**Comment by cwb124** [comment]
Attached is uaa.log
[uaa.txt](https://github.com/cloudfoundry/uaa-release/files/1201523/uaa.txt)

I am leaning toward a cert issue but I can't confirm nor am I sure how to fix it if that's the case.

**Comment by cwb124** [comment]
Anyone have a chance to take a look. At a complete stand still over this issue.

**Comment by agalazis** [comment]
same here

**Comment by tnwang** [comment]
Looks like it was a mismatch of certificate to signing key within your manifest per the logs, and you had resolved this in the cf-deployment linked issue.

**Comment by forexamplelyr** [comment]
so do you fix the problem？
