### ISSUE TITLE
No config to turn off "OpenID Connect RP-Initiated Logout" when using an external OIDC provider

### ISSUE THREAD

**Issue by peterhaochen47** [cloudfoundry/uaa-release#701]
# Current behavior
* Configure UAA to use an [external OIDC provider](https://docs.cloudfoundry.org/api/uaa/version/76.25.0/index.html#oauth-oidc)
* Log into UAA via the external OIDC login
* Click UAA logout button
* See that the user is redirected to the external OIDC provider logout endpoint

In this case, UAA acts as an RP (relying party) to the OP (OIDC provider). This "OpenID Connect RP-Initiated Logout" behavior is defined by this [OIDC spec](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) (note that the spec does not require that RPs must initiate this logout, just provides an option for RPs to do so). 

# Problem statement
This "OpenID Connect RP-Initiated Logout" behavior is sometimes not what UAA operators want. [This Okta discussion](https://developer.okta.com/blog/2020/03/27/spring-oidc-logout-options) talks about how whether an operator wants this behavior highly depends on their use cases (in general, they likely do not want this under a one-OP-multiple-RPs system). 

Currently, UAA offers no config (API, uaa bosh release, or uaa.yml) to opt out of this behavior.

# Proposal
Add an [external OIDC provider](https://docs.cloudfoundry.org/api/uaa/version/76.25.0/index.html#oauth-oidc) config field that controls whether "OpenID Connect RP-Initiated Logout" is performed after logging out of UAA. Default to the current behavior (does perform the RP-Initiated Logout) to avoid a breaking change.

The uaa-release level config [login.oauth.providers](https://github.com/cloudfoundry/uaa-release/blob/7b35b750bf0cb5d50597dff2598af2462ae52a44/jobs/uaa/spec#L1026) should have this config as well.

**Comment by strehle** [comment]
There is no option in Bosh for a global behavior but if you would create your OIDC provider similar to what is described in

https://docs.cloudfoundry.org/api/uaa/version/76.25.0/index.html#oauth-oidc

then the logout would not be triggered.

Why. 
You can create OIDC providers with 2 options,
a) with discoveryUrl
b) with tokenUrl ,  authUrl , logoutUrl etc. only

If logoutUrl is not set here, because Google for example does not provide it in OIDC metadata, then it wont be called.
So maybe with option b) it works for you?

Does UAA have similar option for SAML2 ?

**Comment by peterhaochen47** [comment]
> If logoutUrl is not set here, because Google for example does not provide it in OIDC metadata, then it wont be called.
So maybe with option b) it works for you?

In our use case, the `discoveryUrl` option is used because it's a simpler operator UX, and there's no easy way to change it. 


> Does UAA have similar option for SAML2 ?

I don't see a API or uaa-release config for SAML. [Based on this test](https://github.com/cloudfoundry/uaa/blob/a4ec677f17fed8f5d49186ec20f9145734de6294/uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/SamlLoginIT.java#L436), UAA does not initiate an external SAML logout only when the SAML XML Metadata lacks a SAML logout URL. 


For your comment in Slack:
> A local logout is something I see as feature we can have, but then I would offer this with an option in logout.do (or create one endpoint for local one for global logout) . So I would let the decision to the callee and not to the admin (Bosh option). 

Focusing on the specific use case in **our org first**:
* Almost all of our UAA client apps are just internal components within the same system (e.g. CF components), so whether UAA initiates "RP-Initiated Logout" is more of a system-wide decision rather than an individual client app decision. So it's more convenient on our side to let it be a UAA operator level config. 
* Also, letting the UAA client apps decide (e.g. via a param for UAA logout.do) does not cover the case where you are clicking the logout button on UAA UI directly. 

Broadening to the more general use cases outside of our org:
*  I think letting a UAA client app **alone** decide "whether when their users log out of the app, the users also automatically get logged out of **UAA**" is fair, in most cases. This is the status quo today: client apps can choose to opt-in to this behavior with the UAA logout.do endpoint. 
   * One might argue that this is giving clients too much power (because they now have the power to end user's session with UAA, which might impact all the other clients; this is likely why those "super OIDC providers" like Google do not offer this feature to clients?), but I don't think we have received feedback that this is a significant issue for UAA?
* However, letting a UAA client app **alone** decide "whether when their users log out of the app, the users also automatically get logged out of **the external OIDC provider that UAA's integrated with**" might be giving client apps too much power, because the impact is now much broader, affecting not only all the other UAA clients, but also the clients of the external OIDC provider. 
  * However, I do think this allocation of power could be fair in some cases. So perhaps if there's enough demand for this client-level config (letting the UAA client apps decide), we could add both the client-level config (a param for UAA logout.do, or maybe the client config) and the operator-level config (uaa-release, API)? So that operators can choose to allow client apps to have this power, or not. And the RP-initiated logout only happens if 1) operator allows it, AND 2) client chooses to trigger it (or does not turn if off, depending on what the default behavior is).

**Comment by strehle** [comment]
ok, but if we add an option , then I would do it in config of https://docs.cloudfoundry.org/api/uaa/version/76.25.0/index.html#oauth-oidc
means the setting would be per OIDC IdP ? So the issue should be moved to UAA because we dont need a bosh setting. ? or did I missing something

**Comment by peterhaochen47** [comment]
Yes, adding it to the config per external OIDC provider is the proposal. 
You can add an external provider [via uaa-release](https://github.com/cloudfoundry/uaa-release/blob/7b35b750bf0cb5d50597dff2598af2462ae52a44/jobs/uaa/spec#L1026) too. It's best to keep all three settings consistent (uaa-release, API, uaa.yml). But you are right, the main code change would be in UAA src and perhaps uaa-release only needs a change in the example configs in the spec file, or maybe more if the BOSH manifest is validated in uaa-release (this issue can be used to track that work). 

I just opened an equivalent issue in UAA: https://github.com/cloudfoundry/uaa/issues/2589

**Comment by torsten-sap** [comment]
> A local logout is something I see as feature we can have, but then I would offer this with an option in logout.do (or create one endpoint for local one for global logout) . So I would let the decision to the callee and not to the admin (Bosh option).

I think such a local logout could also be helpful for [OIDC front-channel SLO](https://openid.net/specs/openid-connect-frontchannel-1_0.html).

Imagine a few clients (e.g. UAAs) have a session with the same OIDC IdP. And the user logs out from the IdP directly. Afterwards the IdP calls the SLO endpoints of all connected clients. Consequently, these clients terminate the local session but would also call the IdP again (if I am not mistaken).
