### ISSUE TITLE
UAA pre-start does not play well with os-conf ca_certs job

### ISSUE THREAD

**Issue by DRuggeri** [cloudfoundry/uaa-release#71]
The UAA pre-start script [examines the certificates in /etc/ssl/certificates/ca_certs.pem and adds every certificate found into the truststore for uaa](https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/bin/pre-start#L18). This causes issues when the [os-conf ca_certs job](http://bosh.io/jobs/ca_certs?source=github.com/cloudfoundry/os-conf-release) is also on the machine because pre-start scripts are [started in parallel](https://bosh.io/docs/job-lifecycle.html).
 - The os-conf ca_certs job adds the certs for which it is responsible and then calls update-ca-certificates. This means uaa pre-start script will not see the certs os-conf ca_certs added (since it has already obtained an index of number of certs)
 - If anything calls update-ca-certificates while the uaa pre-start job is running, [the very short period of time where update-ca-certificates deletes and recreates /etc/ssl/certificates/ca_certs.pem](https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/854927) will cause the pre-start job to fail with a file not found error

This is agreeably a limited use case. In my case, I want to run UAA for the BOSH director colocated with the BOSH director. In order to get the BOSH director itself to trust our internally issued certs, I was trying to use os-conf ca_certs job.

**Comment by DRuggeri** [comment]
I forked the repo and prepared a simple patch... but it feels... ugly and gross. To avoid the case when update-ca-certs is called while the file is being processed, a temporary copy is created and used during the truststore building. To avoid the 'race condition' with os-conf ca_certs, I added a sleep statement.

**Comment by DRuggeri** [comment]
Any feedback? Been a while....

**Comment by DennisDenuto** [comment]
fyi: @DRuggeri feedback left on https://github.com/cloudfoundry/uaa-release/pull/72

**Comment by DRuggeri** [comment]
Yikes - sorry I missed it! I'll reply there. Thanks!

**Comment by poblin-orange** [comment]
hitting same issue. Eager to have the fix :-)

**Comment by DennisDenuto** [comment]
`uaa-release` should be compatible with `os-conf`. see:  https://github.com/cloudfoundry/uaa-release/commit/61ae508f5344bd31322d6301379e4320540180bb
