### ISSUE TITLE
Configuration of UAA as OIDC provider and external SAML authentication

### ISSUE THREAD

**Issue by philippthun** [cloudfoundry/uaa-release#73]
Hi,

When using the default configuration of `uaa-release` with regards to `uaa.issuer` and `login.saml.entity_base_url` (as is done both in `cf-release` and `cf-deployment`), you end up with:
- `uaa.issuer = https://uaa.<system-domain>`
- `login.saml.entity_base_url = login.<system-domain>`

We are using UAA as OIDC provider. The OIDC client requests additional information from the token endpoint by appending `/.well-known/openid-configuration` to the URL. In theory one could either use `https://login.<system-domain>/oauth/token` or `https://uaa.<system-domain>/oauth/token` as token endpoint. But as the `openid-configuration` that is returned also contains a field `issuer` and the value of this field is derived from the `uaa.issuer` property (`https://uaa.<system-domain>/oauth/token`) one has to use `https://uaa.<system-domain>/oauth/token` as token endpoint. Otherwise (using `https://login.<system-domain>/oauth/token` as endpoint and getting `"issuer":"https://uaa.<system-domain>/oauth/token" returned`) OIDC clients have to regard the `openid-configuration` as invalid - URL and `issuer` must match according to the specification.

So we used `https://uaa.<system-domain>/oauth/token` as token endpoint - this works fine as long as we do not also use external SAML authentication. When SAML is enabled, the user can click on the appropriate link and then gets redirected to `https://login.<system-domain>...` (derived from the `login.saml.entity_base_url` property) - this breaks the user's session (different host, i.e. a new session cookie is issued). Although the SAML authentication works fine, the user ends up on `https://login.<system-domain>` as the final redirect back to the application was part of the initial session.

So we changed `uaa.issuer` to `https://login.<system-domain>` (and used `https://login.<system-domain>/oauth/token` as token endpoint in the OIDC client). Then everything works fine...

So our questions now are:
- Is it okay to change `uaa.issuer` to `https://login.<system-domain>` or could there be any side-effects?
- Is the *mismatch* of the default values for `uaa.issuer` and `login.saml.entity_base_url` intended? Should this be documented somewhere (at least that the combination of UAA as OIDC provider and external SAML authentication does not work with these values)?

Thanks,
Philipp

**Comment by philippthun** [comment]
> So we changed `uaa.issuer` to `https://login.<system-domain>` (and used `https://login.<system-domain>/oauth/token` as token endpoint in the OIDC client). Then everything works fine...

We figured out that changing the `uaa.issuer` for a deployment that is already up und running does only work with some hickups. The cloud controller [caches the issuer](https://github.com/cloudfoundry/cloud_controller_ng/blob/3052dc9fc0bbd0026eae090385b8ad1fba14f2c4/lib/cloud_controller/uaa/uaa_token_decoder.rb#L94), i.e. after updating `uaa` there is a mismatch resulting in `Invalid Auth Token` errors when trying to use `cf cli` (tokens are regarded as [bad](https://github.com/cloudfoundry/cloud_controller_ng/blob/3052dc9fc0bbd0026eae090385b8ad1fba14f2c4/lib/cloud_controller/uaa/uaa_token_decoder.rb#L76)). Restarting cloud controller solved this issue. But as this problem results in a downtime, changing the issuer for an existing deployment does not seem to be supported.

**Comment by philippthun** [comment]
Created an issue for cloud controller wrt caching the issuer: https://github.com/cloudfoundry/cloud_controller_ng/issues/977

**Comment by tnwang** [comment]
Hi @philippthun,

OpenID Connect core spec only mentions that issuer should be a URL with https scheme, and that the issuer of the token should match the issuer identifier that the client checks for (which UAA publishes the same value as part of the well-known endpoint for Discovery). You should be able to use the `login.<system-domain>/oauth/token` endpoint perfectly fine regardless of the issuer URL location.

That being said, Entity ID is for SAML and Issuer is for OAuth/OpenID Connect. They are mutually exclusive concepts. Both values are configurable so you can specify any value you want, and what you did with issuer is completely fine. Once it's set, your applications should be able to function regardless of the value, as long as you don't change it again.  

If you do change the issuer, all previous OAuth/OpenID tokens will be invalid once your clients begin recognizing the new issuer identifier (likely from Discovery).

If you do change the SAML entity ID, assuming UAA is the SP, you must also update your IDP to recognize the updated entity ID, or UAA will reject the IDP's SAML responses, as the IDP will be using the previous SAML entity ID.

Regards,

Tian
