### ISSUE TITLE
Expose CORS settings

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/uaa-release#74]
Hi guys

UAA's CORS settings can be configured in [uaa.yml](https://github.com/cloudfoundry/uaa/blob/4.7.1/uaa/src/main/resources/uaa.yml#L312) (possible values are visible in [spring-servlet.xml](https://github.com/cloudfoundry/uaa/blob/4.7.1/uaa/src/main/webapp/WEB-INF/spring-servlet.xml#L107)).

We're especially interested in overwriting the `origins` and `credentials`. 

However, the BOSH release does not expose these config values. Can this be added?

We're happy to provide a PR if welcomed.

**Comment by tnwang** [comment]
Hi @MatthiasWinzeler we'd be happy to take a pull request for this. Would be happy to understand as well what use case is driving the need to configure these.

Thanks,

Tian

**Comment by MatthiasWinzeler** [comment]
@tnwang For our web portal, we're trying to submit a POST XHR request to `/oauth/token` (to log in the user). 

Since this transmits credentials, we need UAA to set `Access-Control-Allow-Credentials` to `true` - that's why we initially thought we need to set `credentials`. However, we figured out that UAA sets this when we declare the request as XHR using `X-Request-With`. This also sets `Access-Control-Allow-Origin` correctly.

There is one last roadblock: UAA's default XHR CORS policy disallows `POST` request. We would like to change that.

Even though we only need to set `cors.xhr.allowed.methods` now, it's probably easiest and most flexible if we expose all config items (as optional) in the BOSH release:

```
- cors.default.allowed.uris
- cors.default.allowed.origins
- cors.default.allowed.headers
- cors.default.allowed.methods
- cors.default.allowed.credentials
- cors.default.allowed.max_age
- cors.xhr.allowed.uris
- cors.xhr.allowed.origins
- cors.xhr.allowed.headers
- cors.xhr.allowed.methods
- cors.xhr.allowed.credentials
- cors.xhr.allowed.max_age
```

What do you think about this?

**Comment by sreetummidi** [comment]
@MatthiasWinzeler PR is welcome for this. We won't be able to get to it any time soon

**Comment by pburkholder** [comment]
Hi - can we reopen this? You have a PR so it would be great to get that approved and merge.  Thanks!
