### ISSUE TITLE
New UAA user doesn't have cloud_controller permission

### ISSUE THREAD

**Issue by zhangtbj** [cloudfoundry/uaa-release#75]
Hi Dear all,

I am trying to use the latest Cloud Foundry and UAA, but I found that I cannot create new user correctly. Because new user doesn't have the cloud_controller.read and cloud_controller.write authorities than old UAA version.

Such as I execute:  `cf create-user bmxsvt1@test.com passw0rd`

Then I login by using it, it reported:

API endpoint: https://api.arm-dev.cc (API version: 2.92.0)
User: bmxsvt1@test
No org or space targeted, use 'cf target -o ORG -s SPACE'
FAILED
Error finding available orgs
**Invalid auth token: Invalid Auth Token**

Then I checked with CF_TRACE=true, I found that the authorities are different than before:

**Old UAA Version:**
{"access_token":"[PRIVATE DATA HIDDEN]","token_type":"[PRIVATE DATA HIDDEN]","refresh_token":"[PRIVATE DATA HIDDEN]","expires_in":599,"scope":"**openid uaa.user cloud_controller.read password.write cloud_controller.write**","jti":"c5084ab1ae10407aba2bb7825e7552af"}

**New UAA Version:**
{"access_token":"[PRIVATE DATA HIDDEN]","token_type":"[PRIVATE DATA HIDDEN]","refresh_token":"[PRIVATE DATA HIDDEN]","expires_in":599,"scope":"**password.write openid uaa.user**","jti":"f5ea18f47e4345e9a447188883871c0c"}

I also cannot see these two authorities in uaa.log:
```
[2017-11-08 08:52:59.732] uaa - 7318 [https-jsse-nio-8443-exec-3] ....  INFO --- Audit: ClientAuthenticationSuccess ('Client authentication success'): principal=cf, origin=[remoteAddress=172.30.124.128, clientId=cf], identityZoneId=[cf]
[2017-11-08 08:52:59.975] uaa - 7318 [https-jsse-nio-8443-exec-3] ....  INFO --- Audit: UserAuthenticationSuccess ('bmxsvt1@test.com'): principal=e7ea814e-a5c1-4cc6-af8b-cd1bd9af2045, origin=[remoteAddress=172.30.124.128, clientId=cf], identityZoneId=[cf]
[2017-11-08 08:53:00.128] uaa - 7318 [https-jsse-nio-8443-exec-3] ....  INFO --- Audit: TokenIssuedEvent ('["password.write","openid","uaa.user"]'): principal=e7ea814e-a5c1-4cc6-af8b-cd1bd9af2045, origin=[client=cf, user=bmxsvt1@test.com], identityZoneId=[cf]
```

But after I can manually add by using:
```
uaac member add cloud_controller.read bmxsvt1@test.com
uaac member add cloud_controller.write bmxsvt1@test.com
```

This user works correctly as before.

But new user still have this issue.

I am not sure if it is related with the first change in new UAA release: https://github.com/cloudfoundry/uaa-release/releases/tag/v43

Or do you know how to add these two authorities as default so that I can create new user with two authorities?

Or is there any error in my configuration for new UAA release?

Thanks a lot all!

**Comment by zhangtbj** [comment]
I found that I create a new zone `cf` and no cc permission in new zone default groups.

I need add it by using `uaac curl -X PUT /identity-zones/cf`

Thanks!

**Comment by tnwang** [comment]
Typically, CC works against the default identity zone (/identity-zones/uaa). Other newly created identity zones aren't meant to be understood by CC by default. You should be updating users in the default zone (`uaa`) for CC to use.
