### ISSUE TITLE
Logout redirect using query parameter like in oauth/authorize

### ISSUE THREAD

**Issue by tkarthick81** [cloudfoundry/uaa-release#77]
Can I supply redirect URI using query parameter to /logout.do.??

It is  possible to redirect to a specific URI on calling logout.do by using redirect URL data in yml configuration. 

I  would like to provide the redirect URI in run time, it would be better to supply the URL using query parameter to /logout.do.

Is it a way same as in oauth/authorize available for /logout.do?
For login we use oauth/authorize?redirect_uri=URL

**Comment by strehle** [comment]
Hi,
yes you can, see 
https://docs.cloudfoundry.org/api/uaa/version/4.8.0/index.html#updating-an-identity-zone

In node links for an identity zone you can define such requirement.
    "links" : {
      "logout" : {
        "redirectUrl" : "/login",
        "redirectParameterName" : "redirect",
        "disableRedirectParameter" : false,
        "whitelist" : null
      },
regards,

**Comment by tkarthick81** [comment]
Thank you, the redirect works as expected.
