### ISSUE TITLE
Startup taking > 8 minutes

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/uaa-release#79]
I'm trying to start a UAA instance on GCP using the `n1-standard-4` instance type. We're seeing it take around 8.5 minutes for the UAA to start responding to HTTP requests. Monit reports the process as fine the entire time though, since it has written the PID file and the process is running.

I bumped the Tomcat/Catalina log levels to `FINEST` in order to try to see what was happening while it was starting, and it seems to be just spending that whole time loading classes. The logs had just stuff like this taking up the time between initial boot and when the app is finally up and responding to requests:

```
26-Dec-2017 16:46:36.029 FINE [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.loadClass   Loading class from local repository
26-Dec-2017 16:46:36.029 FINE [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.loadClass loadClass(org.springframework.security.web.csrf.InvalidCsrfTokenException, false)
26-Dec-2017 16:46:36.029 FINE [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.loadClass   Searching local repositories
26-Dec-2017 16:46:36.029 FINE [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.findClass     findClass(org.springframework.security.web.csrf.InvalidCsrfTokenException)
26-Dec-2017 16:46:36.029 FINER [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.findClass       findClassInternal(org.springframework.security.web.csrf.InvalidCsrfTokenException)
26-Dec-2017 16:46:36.030 FINE [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.findClass       Returning class class org.springframework.security.web.csrf.InvalidCsrfTokenException
26-Dec-2017 16:46:36.030 FINE [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.findClass       Loaded by ParallelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@63961c42
```

We're seeing this problem with uaa/53.1

Here are the log files from the instance: [upgrade-validation-20171226-114732-235610058.tar.gz](https://github.com/cloudfoundry/uaa-release/files/1587625/upgrade-validation-20171226-114732-235610058.tar.gz)

**Comment by benmoss** [comment]
It seems like the monit config should be fixed so that it doesn't see the UAA as "running" until it's actually capable of serving requests. It looks like https://github.com/cloudfoundry/uaa-release/blob/431334922758547f1ce751bcac262272d9f796f9/jobs/uaa/monit#L17-L20 is maybe trying to do this, but requests on 8989 just hang, so I would bet monit isn't handling timeouts correctly and that's why it continues to say that the UAA is healthy the entire time.

**Comment by benmoss** [comment]
We were able to downgrade to 52.4 and saw our start times go down to ~2 minutes

**Comment by fhanik** [comment]
I think you can set 
    properties:
      uaa:
        bpm:
          enabled: false

and that should take care of it too. We will leave this issue open to see why BPM enabled causes this issue.

**Comment by fhanik** [comment]
Notes from slack. Secure random may be taking too long 

```
02-Jan-2018 14:41:02.046 WARNING [localhost-startStop-1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [233,366] milliseconds.`
```
You can add to the property the value `-Djava.security.egd=file:/dev/./urandom`
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L110

```
uaa:
  catalina_opts: -Djava.security.egd=file:/dev/./urandom -Xmx768m -XX:MaxMetaspaceSize=256m```
```

**Comment by sreetummidi** [comment]
Closing for now. Please re-open if you are seeing issues.
