### ISSUE TITLE
Automatic forwarding to saml provider login

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [cloudfoundry/uaa-release#81]
Hi,

I am currently searching for a way to automatically forward a user to the authentication page of the configured saml provider when accessing the uaa.<systemurl>/login page.
Is there such a feature at the moment? If not, would it be possible to add such a feature? 

Thanks in advance.

Regards,
Benjamin

**Comment by sreetummidi** [comment]
Yes, please disable internal authentication @ https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L503
