### ISSUE TITLE
Removal Notice

### ISSUE THREAD

**Issue by takedownsantana** [cloudfoundry/uaa-release#856]
Dear Cloud Foundry Foundation,

Apura Cyber ​​Security S.A. was hired by VALID.COM to remove content that contains the company's intellectual property or represents a risk to its information security or that violates the terms of use of its services.

Considering that this project is directing requests to our client's IT resources, we cordially request that you remove the following lines:

repo:cloudfoundry/uaa-release
File: spec/compare/bosh-lite-uaa.yml
Line: 182 (valid.com mentions)

Therefore, I cordially request that you remove these lines.

Certain that we will be granted this cordial request, I bid you farewell with the highest regards.

Julius Santana
Lawyer - OABSP 308.238
Apura Cybersecurity.

**Comment by strehle** [comment]
Created https://github.com/cloudfoundry/uaa-release/pull/857 to remove valid.com

**Comment by strehle** [comment]
@takedownsantana We remove valid.com . The use was in example and tests to validate the Redirect Check with patterns like valid.com or invalid.com.

**Comment by takedownsantana** [comment]
Thank you very much.

Can you refresh ou remove these pages that still display the information?

https://raw.githubusercontent.com/cloudfoundry/uaa-release/e6725d421d7ddbb9c6da2464d2a75f93c96bf034/spec/input/bosh-lite.yml

https://raw.githubusercontent.com/cloudfoundry/uaa-release/e6725d421d7ddbb9c6da2464d2a75f93c96bf034/spec/compare/bosh-lite-uaa.yml

**Comment by strehle** [comment]
> Thank you very much.
> 
> Can you refresh ou remove these pages that still display the information?
> 
> https://raw.githubusercontent.com/cloudfoundry/uaa-release/e6725d421d7ddbb9c6da2464d2a75f93c96bf034/spec/input/bosh-lite.yml
> 
> https://raw.githubusercontent.com/cloudfoundry/uaa-release/e6725d421d7ddbb9c6da2464d2a75f93c96bf034/spec/compare/bosh-lite-uaa.yml

until now , there is no release created, but it will come with next one

**Comment by takedownsantana** [comment]
You can't delete these pages?
