### ISSUE TITLE
post-start script http port is hardcoded

### ISSUE THREAD

**Issue by rahulkj** [cloudfoundry/uaa-release#86]
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/bin/health_check#L3

On line 3, we have the port hard coded to `8080`. Could you just read the value from the config file for `uaa.port`?

**Comment by DennisDenuto** [comment]
Thanks for creating this issue. I think this is a good idea. We should be reading the port value from https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L111-L113

It looks like the `monit` file should also have a similar change made to it too. https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/monit#L7

This makes me wonder, what is the behavior of the standalone `uaa` (that uses the monit file) and `uaa` with `route-registrar` that uses the `health_check` script if the `uaa.port` is changed to non 8080 port?

@tnwang I think this *might* be a bug.

**Comment by rahulkj** [comment]
I ran into the issue while deploying bosh and concourse with the latest UAA, and I had to set the port 8080 explicitly for `uaa.port`. People are soon going to run into this issue once they upgrade concourse and bosh to v57 of uaa

**Comment by DennisDenuto** [comment]
@rahulkj Thanks again for creating this issue. You are correct. We are working on a fix for this and will be available soon in the next release.

**Comment by DennisDenuto** [comment]
Fixed on https://github.com/cloudfoundry/uaa-release/releases/tag/v57.1
