### ISSUE TITLE
Can't provide custom CA for database TLS

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/uaa-release#88]
We'd like to use the `tls_enabled` [property](https://bosh.io/jobs/uaa?source=github.com/cloudfoundry/uaa-release&version=57.1#p%3duaadb.tls_enabled) for our UAA db. However we are using a self-signed root CA for our DB, and so would ideally like to provide that cert to the UAA to trust for establishing the connection. It seems UAA is missing a way to specify this though, would it be possible to have it added? Or is the recommended solution to add the custom CA to the system store somehow?

**Comment by DennisDenuto** [comment]
Thanks for creating this issue, AFAIK you cannot set a `ca cert` on the [datasource](https://github.com/cloudfoundry/uaa/blob/9c80e26e6f4015edf0ed92e06e8d40c732428f1d/server/src/main/resources/spring/data-source.xml#L27) we are using.

I think the way you can add a `ca cert` for `uaa` to use would be to add it to the `jdk truststore`. You can use the [os-conf release](https://github.com/cloudfoundry/os-conf-release) to add certs to the `uaa` truststore. 

See this ops file we use in our [uaa acceptance tests](https://github.com/cloudfoundry/uaa-release/blob/develop/src/acceptance_tests/uaa-release_test.go#L41-L43) as an example on how to co-locate the os-conf with the uaa to add a ca cert to the truststore: https://github.com/cloudfoundry/uaa-release/blob/develop/src/acceptance_tests/opsfiles/os-conf-1-certificate.yml

**Comment by benmoss** [comment]
@DennisDenuto that makes sense. What I realize we are doing on CredHub is accepting the database CA certificate as a spec property and then automatically adding it to the jdk truststore for our users if its provided (https://github.com/pivotal-cf/credhub-release/blob/245fb799d137b170ffb45a04415e1351e56417ad/jobs/credhub/templates/init_key_stores.erb#L60-L66)

Doing it via the os-conf release makes sense too. Thanks.

**Comment by bhadana-rajesh** [comment]
Hi @DennisDenuto,

 I am trying to add ca certificate for Azure MySQL service in UAA jdk truststore.  

error message in UAA logs  : 2021-02-16T10:40:57.42+0000 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.tomcat.jdbc.pool.ConnectionPool         SEVERE  Unable to create initial connections of pool.
   2021-02-16T10:40:57.42+0000 [APP/PROC/WEB/0] OUT java.sql.SQLInvalidAuthorizationSpecException: SSL connection is required. Please specify SSL options and retry.

the example link you mentioned in above comment is not working https://github.com/cloudfoundry/uaa-release/blob/develop/src/acceptance_tests/opsfiles/os-conf-1-certificate.yml

can you share steps how to configure ca certificate or guide me how it should be done.

Thanks,
Rajesh
