### ISSUE TITLE
LDAP certificate issue

### ISSUE THREAD

**Issue by momchil-sap** [cloudfoundry/uaa-release#9]
Hi,

With the introduction of `uaa-release` a breaking change to the UAA has been added. It is no longer possible to configure an LDAP store with a self-signed certificate.

The problem is that the following line references a folder that does not exists:
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/templates/install_crt#L11

When UAA is started it fails to store the certificate and communication with the LDAP is not allowed.

This problem can be fixed by replacing the above line with the following:

```bash
TRUST_STORE_FILE=$JDK_HOME/jre/lib/security/cacerts
```

(Notice the added `jre` segment)

It seems that with the introduction of `uaa-release` an update was done on the JDK:
https://github.com/cloudfoundry/cf-release/blob/v226/packages/uaa/spec#L7-L9
https://github.com/cloudfoundry/uaa-release/blob/v4/packages/uaa/spec#L6-L8

This newer JDK package has a different folder structure and the `security` folder is now located in the `jre` subfolder of the JDK.

It seems strange that this would happen for just a bug-fix increment of the JDK. Are you doing some type of repackaging yourself or are the JDK tgz files official?

Either the `install_crt` script file needs to be adapted or the packaging (if custom) of the JDK needs to be restored to its old state.

**Comment by sreetummidi** [comment]
Fixed in V12 and above
