### ISSUE TITLE
Update issue Add_Identity_Zone_Active DB extend

### ISSUE THREAD

**Issue by renelehmann** [cloudfoundry/uaa-release#98]
We have seen twice an UAA update issue on different CF installations.
On both environments we started the update from UAA v62.0 to v64.0 and in one case to v66.0.

The update of the first instance (canary) failed during post-start:
post-start scripts failed. Failed Jobs: uaa

Unfortunately we did not have enough time to investigate why this happened and 
we cannot provide any logs. But in one case we observed a database duplicate error.

On both situations it helped to revert the sql statement and delete the schema_version entry:
`https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_21_0__Add_Identity_Zone_Active.sql`

Action:
```
ALTER TABLE identity_zone drop column active;
DELETE FROM schema_version where installed_rank='73';
```

Afterwards UAA solved the problem by itself, the DB extend was back again and UAA could start successfully.

**Comment by strehle** [comment]
outdated
